name: Build and Deploy

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Replace with your desired Python version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer==1.2.0 cython==0.29.21 kivy==2.0.0 kivymd==0.104.1
    
    - name: Build APK
      run: |
        buildozer init
        buildozer android debug
